# Generated by Django 5.0.9 on 2024-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_search_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phonenum', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='search_images/')),
                ('ssn', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
