# Generated by Django 5.0.9 on 2024-10-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_biodata_delete_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BioData',
            new_name='Person',
        ),
    ]
