# Generated by Django 5.0.9 on 2024-10-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_rename_biodata_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='search_images/'),
        ),
    ]
