# Generated by Django 5.0.9 on 2024-10-18 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_used', models.CharField(max_length=255)),
                ('bvn', models.CharField(max_length=11, unique=True)),
                ('nin', models.CharField(max_length=11, unique=True)),
                ('account_number', models.CharField(max_length=10, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='search.person')),
            ],
        ),
    ]
